### ISSUE TITLE
.devcontainer missing

### ISSUE THREAD

**Issue by derkaan** [rails/rails-new#20]
Hi, 

it looks like that the "--devcontainer" argument is not working as expected.
At least it doesn't create according .devcontainer directory nor config.

I tried it with the last two releases v0.3.0 and 0.2.1 on a Mac M1 Pro.

```bash
rails-new -V                                                                                                2 ↵
rails-new 0.3.0

# I followed the instructions from here: https://edgeguides.rubyonrails.org/getting_started_with_devcontainer.html
# this is the command I used 
rails-new blog --devcontainer
```

Am I missing something?

**Comment by onshi** [comment]
Hey there, 

your command is fine, but I believe `--devcontainer` flag is introduced in `rails:7.2.0` version (https://github.com/rails/rails/pull/50914), current `rails-new` binary is being build against `rails:7.1.3` so unfortunately it won't work. 

I ran your command with `rails-new` binary using `rails:7.2.0.beta2` and files below were created. So you can manually create them or wait for new release of `rails-new` :) 

<details>
<summary>blog/.devcontainer/Dockerfile</summary>

```Dockerfile
# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.3.3
FROM ghcr.io/rails/devcontainer/images/ruby:$RUBY_VERSION
``` 

</details>

<details>
<summary>blog/.devcontainer/compose.yaml</summary>

```yaml
name: "blog"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
    - default

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
    - 45678:45678
    depends_on:
    - selenium
    - redis

  selenium:
    image: seleniarm/standalone-chromium
    restart: unless-stopped
    networks:
    - default

  redis:
    image: redis:7.2
    restart: unless-stopped
    networks:
    - default
    volumes:
    - redis-data:/data

  
volumes:
  redis-data:
```

</details>

<details>
<summary>blog/.devcontainer/devcontainer.json</summary>

```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/ruby
{
  "name": "blog",
  "dockerComposeFile": "compose.yaml",
  "service": "rails-app",
  "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",

  // Features to add to the dev container. More info: https://containers.dev/features.
  "features": {
    "ghcr.io/devcontainers/features/github-cli:1": {},
    "ghcr.io/rails/devcontainer/features/activestorage": {},
    "ghcr.io/rails/devcontainer/features/sqlite3": {}
  },

  "containerEnv": {
    "CAPYBARA_SERVER_PORT": "45678",
    "SELENIUM_HOST": "selenium",
    "REDIS_URL": "redis://redis:6379/1"
  },

  // Use 'forwardPorts' to make a list of ports inside the container available locally.
  "forwardPorts": [3000, 6379],

  // Configure tool-specific properties.
  // "customizations": {},

  // Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
  // "remoteUser": "root",


  // Use 'postCreateCommand' to run commands after the container is created.
  "postCreateCommand": "bin/setup"
}
```

</details>
